

def get_book_info():
    """
    Function to prompt the user the book title, book ISNB, author last name, author first name, book publisher,
    year published and book price properly formatting the data.
    :return: new book format separated by forward slash (/)
    """
    book_title = input("Enter book title: ").strip().title()
    book_isbn = input("Enter book ISBN: ").strip()
    book_author_last_name = input("Enter author last name: ").strip().title()
    book_publisher = input("Enter book published: ").strip().title()
    year_published = input("Enter year publisher: ")
    book_price_in_cad = float(input("Enter price: "))
    book_info = book_title, book_isbn, book_author_last_name, book_publisher, year_published, "{:.2f}".format(book_price_in_cad)
    new_book_format = "/".join(book_info)
    return new_book_format


def to_csv_format(book_information) -> object:
    """
    Function that takes the string generated by get book info converting it to a CSV format.
    :param book_information:
    :return:CSV format
    """
    csv_format = "{}".format(book_information).split("/")
    csv_format_join = ",".join(csv_format)
    return csv_format_join


def to_json_format(csv_format):
    """
    Function that takes a CSV format string  converting it to a JSON format.
    :param csv_format:
    :return: JSON format
    """
    data = str(csv_format)
    split_data = data.split(",")
    json_format = f'{{"title":"{split_data[0]}",' \
                  f'"isbn":"{split_data[1]}",' \
                  f'"author_last_name":"{split_data[2]}",' \
                  f'"book_publisher":"{split_data[3]}",' \
                  f'"year_published":"{split_data[4]}",' \
                  f'"price":"{split_data[5]}"}}'
    return json_format


def main():
    book_data = get_book_info()
    csv_string = to_csv_format(book_data)
    json_string = to_json_format(csv_string)
    print(f'The CSV Format String:\n{csv_string}')
    print(f'The JSON Format String:\n{json_string}')


if __name__ == "__main__":
    main()
